/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Modelos.Etiqueta;
import Modelos.Servidor;
import Modelos.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fer
 */
public class Preguntar extends javax.swing.JPanel {

    /**
     * Creates new form Preguntar
     */
    Servidor unServidor;
    Usuario unUsuario;
    Principal unPrincipal;
    public Preguntar(Servidor server, Usuario user, Principal princ) {
        this.unServidor=(Servidor)server;
        this.unUsuario=(Usuario)user;
        this.unPrincipal=(Principal)princ;
        initComponents();
        this.lblErrorTitulo.setVisible(false);
        this.lblErrorEtiq.setVisible(false);
        this.lblErrorCuerpo.setVisible(false);
    }

    public ArrayList etiquetas(String etiq){
        String arrayString[]=etiq.toLowerCase().split(" ");
        ArrayList lista=new ArrayList();
        
        for (String a:arrayString){
            if(!this.unServidor.existeEtiqueta(a)){
                this.unServidor.crearEtiqueta(a);
            }
            lista.add(this.unServidor.getEtiquetas().get(a));
        }
        return lista;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblCuerpo = new javax.swing.JLabel();
        scrollCuerpo = new javax.swing.JScrollPane();
        txtCuerpo = new javax.swing.JTextArea();
        lblEtiquetas = new javax.swing.JLabel();
        txtEtiquetas = new javax.swing.JTextField();
        btnPublicar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblErrorTitulo = new javax.swing.JLabel();
        lblErrorCuerpo = new javax.swing.JLabel();
        lblErrorEtiq = new javax.swing.JLabel();

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblTitulo.setText("Título");

        lblCuerpo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblCuerpo.setText("Cuerpo [Breve descripción del problema]");

        txtCuerpo.setColumns(20);
        txtCuerpo.setRows(5);
        scrollCuerpo.setViewportView(txtCuerpo);

        lblEtiquetas.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblEtiquetas.setText("Etiquetas");

        btnPublicar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnPublicar.setText("Publica tu pregunta");
        btnPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        lblErrorTitulo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblErrorTitulo.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorTitulo.setText("Ingrese un título!");

        lblErrorCuerpo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblErrorCuerpo.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorCuerpo.setText("Ingrese descripción!");

        lblErrorEtiq.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblErrorEtiq.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorEtiq.setText("Ingrese al menos una etiqueta!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEtiquetas)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErrorEtiq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuerpo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollCuerpo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblErrorTitulo)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblErrorTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuerpo)
                    .addComponent(lblErrorCuerpo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiquetas)
                    .addComponent(txtEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorEtiq)
                    .addComponent(btnPublicar))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarActionPerformed
        // TODO add your handling code here:
        this.lblErrorTitulo.setVisible(false);
        this.lblErrorEtiq.setVisible(false);
        this.lblErrorCuerpo.setVisible(false);
        
        String titulo=this.txtTitulo.getText();
        String cuerpo=this.txtCuerpo.getText();
        String etiquetas=this.txtEtiquetas.getText();
        if(titulo.length()>0 && cuerpo.length()>0 && etiquetas.length()>0){
            ArrayList lista= this.etiquetas(etiquetas);
            this.unUsuario=(Usuario)this.unPrincipal.getUser();
            this.unServidor.publicarPregunta(titulo, cuerpo, lista, this.unUsuario);
            //this.unServidor.buscarUsuario("pepe");
            Preguntas pnlPreguntas= new Preguntas(this.unPrincipal, this.unPrincipal.getUser() ,this.unServidor);
            JOptionPane.showMessageDialog(null, "Pregunta publicada!","SQUestions",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/vistoPositivo.png"));
            this.unPrincipal.devolverScroll().setViewportView(pnlPreguntas);
        }else if(titulo.length()==0){
            this.lblErrorTitulo.setVisible(true);
        }else if(cuerpo.length()==0){
            this.lblErrorCuerpo.setVisible(true);
        }else if(etiquetas.length()==0){
            this.lblErrorEtiq.setVisible(true);
        }
        
    }//GEN-LAST:event_btnPublicarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublicar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCuerpo;
    private javax.swing.JLabel lblErrorCuerpo;
    private javax.swing.JLabel lblErrorEtiq;
    private javax.swing.JLabel lblErrorTitulo;
    private javax.swing.JLabel lblEtiquetas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrollCuerpo;
    private javax.swing.JTextArea txtCuerpo;
    private javax.swing.JTextField txtEtiquetas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
