/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Excepciones.UsuarioException;
import Hilos.FechaHora;
import Modelos.Servidor;
import Modelos.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JScrollPane;

/**
 *
 * @author Fer
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Servidor unControl=null;
    Usuario unUsuario=null;

    
    public Principal(Servidor control) {
        this.unControl=(Servidor) control;
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Logo_Pibe-M.png"));
        setIconImage(icon);
        fechaHora();
        
        this.lblUser.setText(" ");
        this.lblCorreo.setText(" ");
        this.btnPreguntar.setVisible(false);
        this.btnCerrarSesion.setVisible(false);
        this.btnMisDatos.setVisible(false);
        Preguntas pnlPreguntas= new Preguntas(this, this.unUsuario, this.unControl);
        this.scrollPrincipal.setViewportView(pnlPreguntas);
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/Logo_Pibe-M.png"));
        return retValue;
    }
    public void crearUsuarioSimple(String nombre, String correo, String contraseña) throws UsuarioException{
        this.unControl.crearUsuarioSimple(nombre, contraseña, correo);
    }
    
    public void iniciarSesion(Usuario unUsuario){
        this.unUsuario=(Usuario)unUsuario;
        this.lblUser.setText("Usuario: "+this.unUsuario.toString());
        this.lblCorreo.setText("Correo: "+this.unUsuario.getCorreo());
        this.btnIniciarSesion.setVisible(false);
        this.btnRegistrarse.setVisible(false);
        this.btnPreguntar.setVisible(true);        
        this.btnCerrarSesion.setVisible(true);
        this.btnMisDatos.setVisible(true);
    }
    
    public Usuario getUser(){
        return this.unUsuario;
    }

    public void fechaHora(){
        FechaHora fecha= new FechaHora();
        fecha.setUnLabel(lblDia);
        fecha.start();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlNegro = new javax.swing.JPanel();
        btnRegistrarse = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        btnMisDatos = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblSQU = new javax.swing.JLabel();
        btnPreguntas = new javax.swing.JButton();
        btnEtiquetas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnInsignias = new javax.swing.JButton();
        lblEstions = new javax.swing.JLabel();
        btnPreguntar = new javax.swing.JButton();
        scrollPrincipal = new javax.swing.JScrollPane();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblDia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SQUestions");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlNegro.setBackground(new java.awt.Color(0, 0, 0));

        btnRegistrarse.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistrarse.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setContentAreaFilled(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.setFocusPainted(false);
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        btnIniciarSesion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnMisDatos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMisDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnMisDatos.setText("Mis Datos");
        btnMisDatos.setBorderPainted(false);
        btnMisDatos.setContentAreaFilled(false);
        btnMisDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMisDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciarSesion))
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnIniciarSesion)
                .addComponent(btnMisDatos)
                .addComponent(btnCerrarSesion))
        );

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.jpg"))); // NOI18N

        lblSQU.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSQU.setText("SQU");

        btnPreguntas.setBackground(new java.awt.Color(102, 102, 102));
        btnPreguntas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPreguntas.setText("Preguntas");
        btnPreguntas.setBorderPainted(false);
        btnPreguntas.setContentAreaFilled(false);
        btnPreguntas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });

        btnEtiquetas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEtiquetas.setText("Etiquetas");
        btnEtiquetas.setBorderPainted(false);
        btnEtiquetas.setContentAreaFilled(false);
        btnEtiquetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnUsuarios.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnInsignias.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnInsignias.setText("Insignias");
        btnInsignias.setBorderPainted(false);
        btnInsignias.setContentAreaFilled(false);
        btnInsignias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblEstions.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEstions.setText("estions");

        btnPreguntar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPreguntar.setText("Preguntar");
        btnPreguntar.setBorderPainted(false);
        btnPreguntar.setContentAreaFilled(false);
        btnPreguntar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPreguntar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreguntarMouseClicked(evt);
            }
        });
        btnPreguntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntarActionPerformed(evt);
            }
        });

        scrollPrincipal.setBorder(null);

        jXSearchField1.setPrompt("Buscar preguntas");

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        lblUser.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User");

        lblCorreo.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo");

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Nueva instancia");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUser)
                .addComponent(lblCorreo)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblDia.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblDia.setText("21:37 Viernes, 21/11/2014");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPrincipal)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSQU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagen)
                .addGap(74, 74, 74)
                .addComponent(btnPreguntas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEtiquetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsignias)
                .addGap(14, 14, 14)
                .addComponent(btnPreguntar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDia))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSQU)
                            .addComponent(lblEstions)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPreguntar)
                            .addComponent(btnInsignias)
                            .addComponent(btnUsuarios)
                            .addComponent(btnEtiquetas)
                            .addComponent(btnPreguntas)
                            .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        InicioSesion pnlSesion= new InicioSesion(this.unControl,this);
        this.scrollPrincipal.setViewportView(pnlSesion);
        
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        // TODO add your handling code here:
        Preguntas pnlPreguntas= new Preguntas(this, this.unUsuario, this.unControl);
        this.scrollPrincipal.setViewportView(pnlPreguntas);
    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void btnPreguntarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreguntarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreguntarMouseClicked

    private void btnPreguntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntarActionPerformed
        // TODO add your handling code here:
        Preguntar pnlPregunta= new Preguntar(this.unControl, this.unUsuario, this);
        this.scrollPrincipal.setViewportView(pnlPregunta);
        
    }//GEN-LAST:event_btnPreguntarActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        Registrarse pnlRegistro= new Registrarse(this, this.unControl);
        this.scrollPrincipal.setViewportView(pnlRegistro);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal nuevoPrincipal= new Principal(this.unControl);
        nuevoPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public JScrollPane devolverScroll(){
        return this.scrollPrincipal;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Servidor control) {
                new Principal(control).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEtiquetas;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnInsignias;
    private javax.swing.JButton btnMisDatos;
    private javax.swing.JButton btnPreguntar;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblEstions;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSQU;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlNegro;
    private javax.swing.JScrollPane scrollPrincipal;
    // End of variables declaration//GEN-END:variables
}
