/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Modelos.Pregunta;
import Modelos.Respuesta;
import Modelos.Servidor;
import Modelos.Usuario;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fer
 */
public class Responder extends javax.swing.JPanel {

    /**
     * Creates new form Responder
     */
    Servidor unServidor=null;
    Usuario unUsuario=null;
    Pregunta unaPregunta=null;
    ArrayList respuestas=null;
    Principal unPrincipal=null;
    int posicion=0;
    public Responder(Servidor server, Usuario user, Pregunta p, Principal unp) {
        this.unServidor=(Servidor) server;
        this.unUsuario=(Usuario) user;
        this.unaPregunta=(Pregunta) p;
        this.respuestas=(ArrayList)this.unaPregunta.getRespuestas();
        this.unPrincipal=(Principal) unp;
        
        initComponents();
        this.lblTitulo.setText(this.unaPregunta.toString());
        this.lblError.setVisible(false);
        this.txtPregunta.setText(this.unaPregunta.getCuerpo());
        this.lblEtiqueta1.setText(this.unaPregunta.getEtiquetas().toString());
        this.lblUserPregunta.setText(this.unaPregunta.getAutor().toString());
        this.lblFechaPregunta.setText(this.unaPregunta.getFecha());
        
        if(this.unaPregunta.getRespuestas().size()>0){
        this.lblnumRespuesta.setText("1");
        this.lblCanRespuesta.setText(""+this.unaPregunta.getRespuestas().size());
        this.txtRespuesta.setText(this.respuestas.get(posicion).toString());
        Respuesta resp=(Respuesta)this.respuestas.get(posicion);
        this.lblUSerRespuesta.setText(resp.getAutor().toString());
        this.lblFechaRespuesta.setText(resp.getFecha());
        this.btnAnterior.setEnabled(false);
        this.btnSiguiente.setEnabled(false);
        if(this.unaPregunta.getRespuestas().size()>1){
            this.btnSiguiente.setEnabled(true);
        }
        }else{
            this.lblCanRespuesta.setVisible(false);
            this.lblnumRespuesta.setVisible(false);
            this.lblDe.setVisible(false);
            this.btnAnterior.setEnabled(false);
            this.btnSiguiente.setEnabled(false);
            this.lblAutorRespuesta.setVisible(false);
            this.lblUSerRespuesta.setVisible(false);
            this.lblFechaRespuesta.setVisible(false);
            this.lblAutorRespuesta.setVisible(false);
            this.lblPublicadoRespuesta.setVisible(false);
        }
        
        if(this.unUsuario!=null){
            this.lblTuRespuesta.setVisible(true);
            this.scrollTuRespuesta.setVisible(true);
            this.btnResponder.setVisible(true);
        }else{
        this.lblTuRespuesta.setVisible(false);
        this.scrollTuRespuesta.setVisible(false);
        this.btnResponder.setVisible(false);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        scrollPregunta = new javax.swing.JScrollPane();
        txtPregunta = new javax.swing.JTextArea();
        lblEtiquetas = new javax.swing.JLabel();
        lblEtiqueta1 = new javax.swing.JLabel();
        lblRespuesta = new javax.swing.JLabel();
        scollRespuesta = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        btnSiguiente = new javax.swing.JButton();
        lblTuRespuesta = new javax.swing.JLabel();
        scrollTuRespuesta = new javax.swing.JScrollPane();
        txtTuRespuesta = new javax.swing.JTextArea();
        btnResponder = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblnumRespuesta = new javax.swing.JLabel();
        lblDe = new javax.swing.JLabel();
        lblCanRespuesta = new javax.swing.JLabel();
        lblAutorRespuesta = new javax.swing.JLabel();
        lblUSerRespuesta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblError = new javax.swing.JLabel();
        lblPublicadoRespuesta = new javax.swing.JLabel();
        lblFechaRespuesta = new javax.swing.JLabel();
        lblAutorPregunta = new javax.swing.JLabel();
        lblUserPregunta = new javax.swing.JLabel();
        lblPublicadoPregunta = new javax.swing.JLabel();
        lblFechaPregunta = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 51));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblTitulo.setText("Qué es java?");

        txtPregunta.setEditable(false);
        txtPregunta.setColumns(20);
        txtPregunta.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtPregunta.setRows(5);
        txtPregunta.setText("Necesito información específica de ese lenguaje.");
        scrollPregunta.setViewportView(txtPregunta);

        lblEtiquetas.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblEtiquetas.setText("Etiquetas");

        lblEtiqueta1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblEtiqueta1.setText("Java");

        lblRespuesta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblRespuesta.setText("Respuestas");

        txtRespuesta.setEditable(false);
        txtRespuesta.setColumns(20);
        txtRespuesta.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtRespuesta.setRows(5);
        scollRespuesta.setViewportView(txtRespuesta);

        btnSiguiente.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnSiguiente.setText("Siguiente >>");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblTuRespuesta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblTuRespuesta.setText("Tu respuesta");

        txtTuRespuesta.setColumns(20);
        txtTuRespuesta.setRows(5);
        scrollTuRespuesta.setViewportView(txtTuRespuesta);

        btnResponder.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnResponder.setText("Responder");
        btnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderActionPerformed(evt);
            }
        });

        btnAnterior.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnAnterior.setText("<< Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        lblnumRespuesta.setText("1");

        lblDe.setText("de");

        lblCanRespuesta.setText("2");

        lblAutorRespuesta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblAutorRespuesta.setText("Autor");

        lblUSerRespuesta.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblUSerRespuesta.setText("user");

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        lblError.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Ingrese una Respuesta!");

        lblPublicadoRespuesta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblPublicadoRespuesta.setText("Publicado el:");

        lblFechaRespuesta.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblFechaRespuesta.setText("fecha");

        lblAutorPregunta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblAutorPregunta.setText("Autor:");

        lblUserPregunta.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblUserPregunta.setText("User");

        lblPublicadoPregunta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblPublicadoPregunta.setText("Publicado el:");

        lblFechaPregunta.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblFechaPregunta.setText("Fecha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEtiquetas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPublicadoPregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaPregunta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAutorPregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserPregunta))
                    .addComponent(scrollPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(scollRespuesta)
                    .addComponent(scrollTuRespuesta)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEtiqueta1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRespuesta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTuRespuesta, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResponder))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAutorRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUSerRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPublicadoRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnumRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCanRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente)))
                .addGap(63, 63, 63))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblAutorPregunta)
                    .addComponent(lblUserPregunta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiquetas)
                    .addComponent(lblPublicadoPregunta)
                    .addComponent(lblFechaPregunta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEtiqueta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRespuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scollRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior)
                    .addComponent(lblnumRespuesta)
                    .addComponent(lblDe)
                    .addComponent(lblCanRespuesta)
                    .addComponent(lblAutorRespuesta)
                    .addComponent(lblUSerRespuesta)
                    .addComponent(lblPublicadoRespuesta)
                    .addComponent(lblFechaRespuesta))
                .addGap(18, 18, 18)
                .addComponent(lblTuRespuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTuRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResponder)
                    .addComponent(lblError))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        Respuesta respuesta;
        if(posicion>0){
            posicion--;
            respuesta=(Respuesta)this.respuestas.get(posicion);
            this.txtRespuesta.setText(respuesta.toString());
            this.lblUSerRespuesta.setText(respuesta.getAutor().toString());
            this.lblFechaRespuesta.setText(respuesta.getFecha());
            this.lblnumRespuesta.setText(""+(posicion+1));
            this.btnSiguiente.setEnabled(true);
            if(posicion==0){
                this.btnAnterior.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderActionPerformed
        // TODO add your handling code here:
        
        String cuerpo=this.txtTuRespuesta.getText();
        if(cuerpo.length()>0){
        Usuario autor=this.unUsuario;
        this.unServidor.responderPregunta(cuerpo, this.unaPregunta, autor);
        JOptionPane.showMessageDialog(null, "Gracias por tu respuesta!","SQUestions",
            JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/vistoPositivo.png"));
        Preguntas pnlPreguntas= new Preguntas(this.unPrincipal, this.unUsuario, this.unServidor);
        this.jScrollPane1.setViewportView(pnlPreguntas);
        }else{
            this.lblError.setVisible(true);
        }

    }//GEN-LAST:event_btnResponderActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        Respuesta respuesta;
        if(posicion<this.respuestas.size()-1){
            posicion++;
            respuesta=(Respuesta)this.respuestas.get(posicion);
            this.txtRespuesta.setText(respuesta.toString());
            this.lblUSerRespuesta.setText(respuesta.getAutor().toString());
            this.lblFechaRespuesta.setText(respuesta.getFecha());
            this.lblnumRespuesta.setText(""+(posicion+1));
            this.btnAnterior.setEnabled(true);
            if(posicion==this.respuestas.size()-1){
                this.btnSiguiente.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnResponder;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAutorPregunta;
    private javax.swing.JLabel lblAutorRespuesta;
    private javax.swing.JLabel lblCanRespuesta;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblEtiqueta1;
    private javax.swing.JLabel lblEtiquetas;
    private javax.swing.JLabel lblFechaPregunta;
    private javax.swing.JLabel lblFechaRespuesta;
    private javax.swing.JLabel lblPublicadoPregunta;
    private javax.swing.JLabel lblPublicadoRespuesta;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTuRespuesta;
    private javax.swing.JLabel lblUSerRespuesta;
    private javax.swing.JLabel lblUserPregunta;
    private javax.swing.JLabel lblnumRespuesta;
    private javax.swing.JScrollPane scollRespuesta;
    private javax.swing.JScrollPane scrollPregunta;
    private javax.swing.JScrollPane scrollTuRespuesta;
    private javax.swing.JTextArea txtPregunta;
    private javax.swing.JTextArea txtRespuesta;
    private javax.swing.JTextArea txtTuRespuesta;
    // End of variables declaration//GEN-END:variables
}
